version: '3.8'

services:
    database:
        container_name: blub-postgres
        image: postgres:14.2
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: 'exit 0'
    migrations:
        container_name: blub-migrations
        depends_on:
            database:
                condition: service_healthy
        image: liquibase/liquibase:4.11.0
        volumes:
            - ./src/database/migrations:/liquibase/changelog
        command:
            'update --username=${DB_USERNAME} --password=${DB_PASSWORD} --url=${DB_DOCKER_URL}
            --liquibase-schema-name=public --changelogFile="./master.json"'
